### PR TITLE
Implement Property.select via bind to avoid bug

### LINKED ISSUE #317: Exceptions are reported inconsistently
It looks like exceptions in `Property` and `Property<bool>` are treated and reported differently, with each treatment having good and bad sides. The important aspects in question are
- whether an exception in a single test run aborts the entire property test
- whether the correct exception location is reported in the output

**Property:**
```cs
protected void Run(Action action) => action();

[Test]
public void HH_ExceptionInPropertyVoid()
{
    var property =
        from x in Property.ForAll(Gen.Int32(Range.Constant(0, 0)))
        select Run(() =>
        {
            _ = 1 / x != 2; // line 21
        });
    property.Check(); // line 23
}
```

Output:
```
System.Exception : *** Failed! Falsifiable(after 1 test) :
0
This failure can be reproduced by running:
> Property.recheck(1 : Size) ({ Value = 6998132399885834250UL; Gamma = 6257968130275417025UL }) <property>

at Microsoft.FSharp.Core.Operators.Raise[T](Exception exn)
at Hedgehog.ReportModule.tryRaise(Report report) in c:\test\fsharp-hedgehog\src\Hedgehog\Report.fs:line 107
at Hedgehog.Property.check(Property`1 p) in c:\test\fsharp-hedgehog\src\Hedgehog\Property.fs:line 185
at Hedgehog.Linq.PropertyExtensions.Check(Property property) in c:\test\fsharp-hedgehog\src\Hedgehog\Linq\Property.fs:line 90
at Test.HedgehogBased.HedgehogSimpleTests.HH_ExceptionInPropertyVoid() in c:\test\HedgehogBased\HedgehogSimpleTests.cs:line 23
```

Notice that
- Test run and reproduction info (courtesy of Hedgehog) is present
- Stack trace only mentions line 23, in which the property testing is initiated, but not line 21, in which an exception is actually thrown

**Property\<bool\>:**
```cs
[Test]
public void HH_ExceptionInPropertyBool()
{
    var property =
        from x in Property.ForAll(Gen.Int32(Range.Constant(0, 0)))
        select 1 / x != 2; // line 41
    property.Check();
}
```

Output:
```
System.DivideByZeroException :
at Test.HedgehogSimpleTests.<>c.<HH_ExceptionInPropertyBool>b__1_0(Int32 x) in c:\test\HedgehogBased\HedgehogSimpleTests.cs:line 41
at <StartupCode$Hedgehog>.$Property___2.Select@147-4.Invoke(T arg00) in c:\test\fsharp-hedgehog\src\Hedgehog\Linq\Property.fs:line 147
at Hedgehog.Outcome.Map@28-3.Invoke(a x) in c:\test\fsharp-hedgehog\src\Hedgehog\Outcome.fs:line 28
at Hedgehog.Outcome.cata[a, b](Outcome`1 outcome, FSharpFunc`2 failure, FSharpFunc`2 discard, FSharpFunc`2 success) in c:\test\fsharp-hedgehog\src\Hedgehog\Outcome.fs:line 21
at Hedgehog.Outcome.Map[a, b] (FSharpFunc`2 f, Outcome`1 result) in c:\test\fsharp-hedgehog\src\Hedgehog\Outcome.fs:line 25
at Hedgehog.Property.map@67-7.Invoke(FSharpFunc`2 f, Outcome`1 result) in c:\test\fsharp-hedgehog\src\Hedgehog\Property.fs:line 67
at Hedgehog.Tuple.mapSnd[b, c, a] (FSharpFunc`2 f, a x, b y) in c:\test\fsharp-hedgehog\src\Hedgehog\Tuple.fs:line 12
at Hedgehog.GenTuple.mapSnd@12.Invoke(Tuple`2 tupledArg) in c:\test\fsharp-hedgehog\src\Hedgehog\GenTuple.fs:line 12
at Hedgehog.Tree.map[a, b] (FSharpFunc`2 f, Tree`1 _arg1) in c:\test\fsharp-hedgehog\src\Hedgehog\Tree.fs:line 39
at Hedgehog.Gen.map@57-3.Invoke(Tree`1 arg10@) in c:\test\fsharp-hedgehog\src\Hedgehog\Gen.fs:line 57
at Hedgehog.Random.map@39-2.Invoke(Seed seed, Int32 size) in c:\test\fsharp-hedgehog\src\Hedgehog\Random.fs:line 40
at Hedgehog.Random.unsafeRun[a](Seed seed, Int32 size, Random`1 _arg1) in c:\test\fsharp-hedgehog\src\Hedgehog\Random.fs:line 12
at Hedgehog.Random.run[a] (Seed seed, Int32 size, Random`1 r) in c:\test\fsharp-hedgehog\src\Hedgehog\Random.fs:line 15
at Hedgehog.Gen.run@38T.Invoke(Seed seed, Random`1 random) in c:\test\fsharp-hedgehog\src\Hedgehog\Gen.fs:line 39
at Hedgehog.Gen.bindRandom@34.Invoke(Seed seed0, Int32 size) in c:\test\fsharp-hedgehog\src\Hedgehog\Gen.fs:line 41
at Hedgehog.Random.unsafeRun[a](Seed seed, Int32 size, Random`1 _arg1) in c:\test\fsharp-hedgehog\src\Hedgehog\Random.fs:line 12
at Hedgehog.Random.run[a] (Seed seed, Int32 size, Random`1 r) in c:\test\fsharp-hedgehog\src\Hedgehog\Random.fs:line 15
at Hedgehog.Property.loop@143-11.Invoke(Seed seed, Int32 size, Int32 tests, Int32 discards) in c:\test\fsharp-hedgehog\src\Hedgehog\Property.fs:line 153
at Hedgehog.Property.reportWith'(Boolean renderRecheck, Int32 size0, Seed seed, PropertyConfig config, Property`1 p) in c:\test\fsharp-hedgehog\src\Hedgehog\Property.fs:line 165
at Hedgehog.Property.reportWith(PropertyConfig config, Property`1 p) in c:\test\fsharp-hedgehog\src\Hedgehog\Property.fs:line 169
at Hedgehog.Property.report(Property`1 p) in c:\test\fsharp-hedgehog\src\Hedgehog\Property.fs:line 172
at Hedgehog.Property.check(Property`1 p) in c:\test\fsharp-hedgehog\src\Hedgehog\Property.fs:line 185
at Hedgehog.Property.checkBool(Property`1 g) in c:\test\fsharp-hedgehog\src\Hedgehog\Property.fs:line 189
at Hedgehog.Linq.PropertyExtensions.Check(Property`1 property) in c:\test\fsharp-hedgehog\src\Hedgehog\Linq\Property.fs:line 99
at Test.HedgehogBased.HedgehogSimpleTests.HH_ExceptionInPropertyBool() in c:\test\HedgehogBased\HedgehogSimpleTests.cs:line 42
```

Notice that
- There is no Hedgehog header, output starts directly with the exception info
- Stack trace correctly starts with line 41 which actually throws the exception

### PR DESCRIPTION
**Pull request by TysonMN**
Fixes #317

I added tests corresponding to those given in #317 except that they pass when the behavior is correct and fail otherwise.  Then I fixed the issue by implementing `Property.select` via `Property.bind` and especially `Property.ofThrowing`, which maps a thrown exception to `Outcome<_>.Failure`.

### CODE REVIEW

File: src/Hedgehog/Property.fs [hunk 1]
```diff
@@ -195,13 +195,12 @@ module Property =
         g |> bind ofBool |> checkWith config
 
     /// Converts a possibly-throwing function to
-    /// a property by treating "no exception" as success.
-    let ofThrowing (f : 'a -> unit) (x : 'a) : Property<unit> =
+    /// a property by treating an exception a failure.
```
Comment (adam-becker) [inline src/Hedgehog/Property.fs:198]:
```suggestion
    /// a property by treating an exception as a failure.
```

File: src/Hedgehog/Linq/Property.fs [hunk 2]
```diff
@@ -162,7 +162,8 @@ type PropertyExtensions private () =
 
     [<Extension>]
     static member Select (property : Property<'T>, mapper : Func<'T, 'TResult>) : Property<'TResult> =
-        Property.map mapper.Invoke property
+        property
+        |> Property.bind (Property.ofThrowing mapper.Invoke)
```
Comment (adam-becker) [inline src/Hedgehog/Linq/Property.fs:166]: Shouldn't this be how `map` works? I like having the LINQ interface just forward calls, and not having different functionality.

File: tests/Hedgehog.Linq.Tests/LinqTests.cs [hunk 3]
```diff
@@ -1,16 +1,38 @@
...
+                select func();
+            var report = property.Report();
+            Assert.True(report.Status.IsFailed);
+        }
+
+        /*
+         * The main object the following tests is just to make sure that the examples compile.
+         * There's nothing fancy in the properties being tested.
+         */
+
```
Comment (adam-becker) [inline tests/Hedgehog.Linq.Tests/LinqTests.cs:35]: Code style here doesn't match the rest of the code, the braces should be on a separate line.

Comment (TysonMN) [reply tests/Hedgehog.Linq.Tests/LinqTests.cs:38]: Done

File: src/Hedgehog/Linq/Property.fs (hunk 2 above)
Comment (TysonMN) [reply src/Hedgehog/Linq/Property.fs:166]: I would also prefer if each C# method could just forward to its corresponding F# function.  However, that approach doesn't pass the test that I added.  We need to compensate for the fact that CEs in F# are not the same as query syntax in C#.  I don't care much how that is achieved, but I think @altxt is correct that the current behavior is wrong.

File: src/Hedgehog/Property.fs [hunk 4]
```diff
@@ -195,13 +196,12 @@ module Property =
         g |> bind ofBool |> checkWith config
 
     /// Converts a possibly-throwing function to
-    /// a property by treating "no exception" as success.
-    let ofThrowing (f : 'a -> unit) (x : 'a) : Property<unit> =
+    /// a property by treating an exception as a failure.
```
Comment (adam-becker) [inline src/Hedgehog/Property.fs:199]: I like the verbiage here better :+1:

File: src/Hedgehog/Property.fs [hunk 5]
```diff
@@ -81,9 +81,10 @@ module Property =
     let bind (k : 'a -> Property<'b>) (m : Property<'a>) : Property<'b> =
         bindGen (toGen << k) (toGen m) |> ofGen
 
+    let handle (e : exn) =
```
Comment (adam-becker) [inline src/Hedgehog/Property.fs:84]: Let's make this private or internal until we get a better name. As an alternative, let's get a better name now 😅

Comment (TysonMN) [reply src/Hedgehog/Property.fs]: Made it private.  It probably doesn't ever need to be public.

**Comment by adam-becker** [comment]
@TysonMN if you can get this rebased I'll merge it

**Comment by TysonMN** [comment]
Done

**Comment by TysonMN** [comment]
Can you merge now?

Hedgehog.Experimental will have a new release soon and it would be nice to have this and the other bug fixes included.

**Comment by adam-becker** [comment]
> Can you merge now?
> 
> Hedgehog.Experimental will have a new release soon and it would be nice to have this and the other bug fixes included.

Sorry for the delay, this has been merged. 🎉

**Comment by TysonMN** [comment]
No problem. Thanks for merging :)
