### PR TITLE
fix for returning noncharacters from Gen.unicode

### LINKED ISSUE #158: Gen.unicode―Check if a character is one of the noncharacters '\65534', '\65535'.
See https://github.com/hedgehogqa/haskell-hedgehog/pull/154.

### PR DESCRIPTION
**Pull request by jwChung**
I solved the issue #158.

closes #158

### CODE REVIEW

File: src/Hedgehog/Gen.fs [hunk 1]
```diff
@@ -393,11 +393,16 @@ module Gen =
     let latin1 : Gen<char> =
         char '\000' '\255'
 
-    /// Generates a Unicode character, excluding invalid standalone surrogates:
-    /// '\000'..'\65535' (excluding '\55296'..'\57343')
+    /// Generates a Unicode character, excluding noncharacters('\65534', '\65535')
+    /// and invalid standalone surrogates ('\000'..'\65535' excluding '\55296'..'\57343')
```
Comment (moodmosaic) [inline src/Hedgehog/Gen.fs]: It'd be nice if you can keep the lines <= 79-80 chars width, which means this would then look like this:

```
/// Generates a Unicode character, excluding noncharacters
/// ('\65534', '\65535') and invalid standalone surrogates
/// ('\000'..'\65535' excluding '\55296'..'\57343').
```

File: src/Hedgehog/Gen.fs [hunk 2]
```diff
@@ -393,11 +393,16 @@ module Gen =
...
     [<CompiledName("Unicode")>]
     let unicode : Gen<char> =
-        filter (not << System.Char.IsSurrogate) unicodeAll
+
+        let isNoncharacter x =
+            x = Operators.char 65534 || x = Operators.char 65535
+    
+        filter (not << isNoncharacter)
+        <| filter (not << System.Char.IsSurrogate) unicodeAll
```
Comment (moodmosaic) [inline src/Hedgehog/Gen.fs]: Although this would be perfectly fine in Haskell, in F# it's more common to use the forward-pipe operator, as also mentioned by Don Syme in in his 'F# Code I Love' talk(s):

```fsharp
let unicode : Gen<char> =
    let isNonCharacter x =
           x = Operators.char 65534
        || x = Operators.char 65535
    unicodeAll
    |> filter (not << isNonCharacter)
    |> filter (not << System.Char.IsSurrogate)
```

I'd also get rid of those blank lines since the part they're separating is <= 7 LOC.

File: tests/Hedgehog.Tests/GenTests.fs [hunk 3]
```diff
@@ -18,3 +18,16 @@ let ``dateTime creates System.DateTime instances`` count =
     |> List.distinct
     |> List.length
     =! actual.Length
+
+[<Fact>]
+let ``unicode doesn't return any surrogate`` () =
+    let actual = Gen.sample 100 100000 Gen.unicode 
+    List.filter System.Char.IsSurrogate actual =! []
```
Comment (moodmosaic) [inline tests/Hedgehog.Tests/GenTests.fs]: If you're (still) following XUnit Test Patterns, the [Assertion Method](http://xunitpatterns.com/Assertion%20Method.html) is (usually) expected/actual in tests, rather than actual/expected, so this would look like this:

```fsharp
[] =! List.filter System.Char.IsSurrogate actual
```

It's up to you though, whether you'd like to apply this suggestion or not 😃

File: tests/Hedgehog.Tests/GenTests.fs [hunk 4]
```diff
@@ -18,3 +18,16 @@ let ``dateTime creates System.DateTime instances`` count =
...
+
+[<Theory>]
+[<InlineData(65534)>]
+[<InlineData(65535)>]
+let ``unicode doesn't return any noncharacter`` nonchar =
+    let isNoncharacter = (=) <| Operators.char nonchar
+    let actual = Gen.sample 100 100000 Gen.unicode
+    List.filter isNoncharacter actual  =! []
```
Comment (moodmosaic) [inline tests/Hedgehog.Tests/GenTests.fs]: If you're (still) following XUnit Test Patterns, the [Assertion Method](http://xunitpatterns.com/Assertion%20Method.html) is (usually) expected/actual in tests, rather than actual/expected, so this would look like this:

```fsharp
[] =! List.filter isNoncharacter actual
```

It's up to you though, whether you'd like to apply this suggestion or not 😃

File: src/Hedgehog/Gen.fs (hunk 1 above)
Comment (jwChung) [reply src/Hedgehog/Gen.fs]: I did it.

File: src/Hedgehog/Gen.fs (hunk 2 above)
Comment (jwChung) [reply src/Hedgehog/Gen.fs]: I did it. Can I have a question?  LOC means "Lines Of Code" right? Is there a special criterion in the 7 LOC limit?

File: tests/Hedgehog.Tests/GenTests.fs (hunk 3 above)
Comment (jwChung) [reply tests/Hedgehog.Tests/GenTests.fs]: I agree with you. I made the mistake. I did it so.

File: tests/Hedgehog.Tests/GenTests.fs (hunk 4 above)
Comment (jwChung) [reply tests/Hedgehog.Tests/GenTests.fs]: I did it.

**Comment by jwChung** [comment]
@moodmosaic 
When I met you in AutoFixture, my job is not a programmer but transportation planner as forecasting travel demand. However, I was interested in programming and changed my job to a programmer about three years ago. I was not able to do open source activities as I devoted myself to work. If I have spare time, I hope to see you a lot in open source activities. I appreciate your making me more interested in programming.

You're welcome and don't need the housekeeping. :)

File: tests/Hedgehog.Tests/GenTests.fs [hunk 5]
```diff
@@ -18,3 +18,16 @@ let ``dateTime creates System.DateTime instances`` count =
...
+    let actual = Gen.sample 100 100000 Gen.unicode 
+    [] =! List.filter System.Char.IsSurrogate actual
+
+[<Theory>]
+[<InlineData(65534)>]
+[<InlineData(65535)>]
+let ``unicode doesn't return any noncharacter`` nonchar =
+    let isNoncharacter = (=) <| Operators.char nonchar
+    let actual = Gen.sample 100 100000 Gen.unicode
+    [] =! List.filter isNoncharacter actual
```
Comment (jwChung) [inline tests/Hedgehog.Tests/GenTests.fs]: @moodmosaic There is a deterministic approach to test this function? These two tests are a little slow. The test run time on my computer is about twice as slow as before.  Is it OK? or it's better to remove the tests?

Comment (jwChung) [inline tests/Hedgehog.Tests/GenTests.fs]: @moodmosaic There is a deterministic approach to test this function? These two tests are a little slow. The test run time on my computer is about twice as slow as before. Is it OK? or it's better to remove the tests?

File: src/Hedgehog/Gen.fs (hunk 2 above)
Comment (moodmosaic) [reply src/Hedgehog/Gen.fs]: >LOC means "Lines Of Code" right

Right. https://en.wikipedia.org/wiki/Source_lines_of_code

>Is there a special criterion in the 7 LOC limit?

I don't remember where I've first read this, either in Code Complete or Clean Code (or both(?)) 

(There's also another similar 'hint', about method parameters (that they should be <= 3, otherwise passing a custom data type is warranted).)

File: tests/Hedgehog.Tests/GenTests.fs (hunk 5 above)
Comment (moodmosaic) [reply tests/Hedgehog.Tests/GenTests.fs]: Gen.sample looks fine, if you want just lower the *count* (and the *size*) to, perhaps, something like

```
Gen.sample 10 100
```

This should be ~50% faster although I haven't measured it. As long as the examples [run in 10 seconds or less](http://blog.ploeh.dk/2012/05/24/TDDtestsuitesshouldrunin10secondsorless/) we should be good to go.

File: src/Hedgehog/Gen.fs (hunk 2 above)
Comment (jwChung) [reply src/Hedgehog/Gen.fs]: > I don't remember where I've first read this, either in Code Complete or Clean Code (or both(?))

It seems that I haven't met the criterion in Clean Code.

> (There's also another similar 'hint', about method parameters (that they should be <= 3, otherwise passing a custom data type is warranted).)

Yes, I have met it in  Clean Code - the function part.

File: tests/Hedgehog.Tests/GenTests.fs (hunk 5 above)
Comment (moodmosaic) [reply tests/Hedgehog.Tests/GenTests.fs]:
```
$ dotnet test tests/Hedgehog.Tests/Hedgehog.Tests.fsproj
```

```
Build started, please wait...
Build completed.

Test run for [..]Hedgehog.Tests.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

Total tests: 178. Passed: 178. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 9.0759 Seconds
```

So, the whole test suite runs in ~9 seconds.

---

```diff
diff --git a/tests/Hedgehog.Tests/GenTests.fs b/tests/Hedgehog.Tests/GenTests.fs
index 66b2776..ade363f 100644
--- a/tests/Hedgehog.Tests/GenTests.fs
+++ b/tests/Hedgehog.Tests/GenTests.fs
@@ -21,7 +21,7 @@ let ``dateTime creates System.DateTime instances`` count =

 [<Fact>]
 let ``unicode doesn't return any surrogate`` () =
-    let actual = Gen.sample 100 100000 Gen.unicode
+    let actual = Gen.sample 10 100 Gen.unicode
     [] =! List.filter System.Char.IsSurrogate actual

 [<Theory>]
@@ -29,5 +29,5 @@ let ``unicode doesn't return any surrogate`` () =
 [<InlineData(65535)>]
 let ``unicode doesn't return any noncharacter`` nonchar =
     let isNoncharacter = (=) <| Operators.char nonchar
-    let actual = Gen.sample 100 100000 Gen.unicode
-    [] =! List.filter isNoncharacter actual
\ No newline at end of file
+    let actual = Gen.sample 10 100 Gen.unicode
+    [] =! List.filter isNoncharacter actual
```

```
$ dotnet test tests/Hedgehog.Tests/Hedgehog.Tests.fsproj
```

```
Build started, please wait...
Build completed.

Test run for [..]Hedgehog.Tests.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

Total tests: 178. Passed: 178. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 5.0906 Seconds
```

Indeed, changing Gen.sample *size* to 10 and *count* to 100 makes those two tests to run faster but also, like you wrote, makes them weaker.

---

Then, let's leave those two as-is for now and we can come back later and tune them if needed.

Comment (jwChung) [reply tests/Hedgehog.Tests/GenTests.fs]: > Then, let's leave those two as-is for now and we can come back later and tune them if needed.

Go for it plz.
